import React from 'react';
import Spinner from 'src/view/shared/Spinner';
import ViewWrapper, {
  viewItemLayout,
} from 'src/view/shared/styles/ViewWrapper';
import {
  formItemLayout,
} from 'src/view/shared/styles/FormWrapper';
import { i18n } from 'src/i18n';
import { Form , Row, Col, Table, Card, Typography} from 'antd';
import ImagesViewer from 'src/view/shared/ImagesViewer';
import CustomCheckboxViewItem from 'src/view/shared/form/items/CustomCheckboxViewItem'


const { Text, Title } = Typography;

const SSASurveyView = (props) => {
  const { record, loading } = props;

  const twoColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 12,
    lg: 12,
    xl: 12,
    style: {
      marginBottom: 24,
    },
  };

  const threeColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 8,
    lg: 8,
    xl: 8,
    style: {
      marginBottom: 24,
    },
  };


  const sexColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 4,
    lg: 4,
    xl: 4,
    style: {
      marginBottom: 24,
    },
  };


  const columns = [
    {
      title: i18n('entities.sSASurvey.fields.No'),
      sorter: true,
      dataIndex: 'no',    },
    {
      title: i18n('entities.sSASurvey.fields.DIMENSIONS'),
      sorter: true,
      dataIndex: 'DIMENSIONS',
    },
    {
      title: i18n('entities.sSASurvey.fields.Indicators'),
      sorter: false,
      dataIndex: 'indicators',
    },
    {
      title: i18n('entities.sSASurvey.fields.value'),
      sorter: true,
      dataIndex: 'value',
    },
  ];


  

  const data =[
    {
      no:'1',
      DIMENSIONS:'School leadership and governance',
      indicators:'15',
      value:'15%'
    },
    {
      no:'2',
      DIMENSIONS:'School Environment and its safety',
      indicators:'8',
      value:'10%'
    },
    {
      no:'3',
      DIMENSIONS:'Curriculum implementation',
      indicators:'15',
      value:'30%'
    },
    {
      no:'4',
      DIMENSIONS:'Community Relations and participation',
      indicators:'4',
      value:'15%'
    },
    {
      no:'5',
      DIMENSIONS:'Teaching and learning',
      indicators:'20',
      value:'30%'
    }
  ]

  const dimensionColumns = [
    {
      title: i18n('entities.sSASurvey.fields.No'),
      sorter: true,
      dataIndex: 'no',   
      width:'5%'
    },
    {
      title: i18n('entities.sSASurvey.fields.Indicator'),
      sorter: true,
      dataIndex: 'indicator',
      width:'50%'
    },
    {
      title: i18n('entities.sSASurvey.fields.1'),
      sorter: true,
      dataIndex: '1',
      width:'10%'
    },
    {
      title: i18n('entities.sSASurvey.fields.2'),
      sorter: true,
      dataIndex: '2',
      width:'10%'
    },
    {
      title: i18n('entities.sSASurvey.fields.3'),
      sorter: true,
      dataIndex: '3',
      width:'5%'
    },
    {
      title: i18n('entities.sSASurvey.fields.4'),
      sorter: true,
      dataIndex: '4',
      width:'5%'
    },
    {
      title: i18n('entities.sSASurvey.fields.5'),
      sorter: true,
      dataIndex: '5',
      width:'5%'
    },
    
  ];

  const dimension1 =[
    {
      no:'1',
      indicator:i18n('entities.dimension1.fields.indicator11'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator11}
        name="indicator11"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator11}
        name="indicator11"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator11}
        name="indicator11"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator11}
        name="indicator11"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator11}
        name="indicator11"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'2',
      indicator:i18n('entities.dimension1.fields.indicator12'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator12}
        name="indicator12"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator12}
        name="indicator12"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator12}
        name="indicator12"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator12}
        name="indicator12"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator12}
        name="indicator12"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'3',
      indicator:i18n('entities.dimension1.fields.indicator13'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator13}
        name="indicator13"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator13}
        name="indicator13"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator13}
        name="indicator13"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator13}
        name="indicator13"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator13}
        name="indicator13"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'4',
      indicator:i18n('entities.dimension1.fields.indicator14'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator14}
        name="indicator14"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator14}
        name="indicator14"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator14}
        name="indicator14"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator14}
        name="indicator14"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator14}
        name="indicator14"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'5',
      indicator:i18n('entities.dimension1.fields.indicator15'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator15}
        name="indicator15"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator15}
        name="indicator15"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator15}
        name="indicator15"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator15}
        name="indicator15"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator15}
        name="indicator15"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'6',
      indicator:i18n('entities.dimension1.fields.indicator16'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator16}
        name="indicator16"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator16}
        name="indicator16"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator16}
        name="indicator16"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator16}
        name="indicator16"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator16}
        name="indicator16"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'7',
      indicator:i18n('entities.dimension1.fields.indicator17'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator17}
        name="indicator17"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator17}
        name="indicator17"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator17}
        name="indicator17"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator17}
        name="indicator17"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator17}
        name="indicator17"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'8',
      indicator:i18n('entities.dimension1.fields.indicator18'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator18}
        name="indicator18"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator18}
        name="indicator18"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator18}
        name="indicator18"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator18}
        name="indicator18"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator18}
        name="indicator18"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'9',
      indicator:i18n('entities.dimension1.fields.indicator19'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator19}
        name="indicator19"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator19}
        name="indicator19"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator19}
        name="indicator19"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator19}
        name="indicator19"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator19}
        name="indicator19"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'10',
      indicator:i18n('entities.dimension1.fields.indicator110'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator110}
        name="indicator110"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator110}
        name="indicator110"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator110}
        name="indicator110"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator110}
        name="indicator110"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator110}
        name="indicator110"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'11',
      indicator:i18n('entities.dimension1.fields.indicator111'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator111}
        name="indicator111"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator111}
        name="indicator111"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator111}
        name="indicator111"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator111}
        name="indicator111"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator111}
        name="indicator111"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'12',
      indicator:i18n('entities.dimension1.fields.indicator112'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator112}
        name="indicator112"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator112}
        name="indicator112"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator112}
        name="indicator112"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator112}
        name="indicator112"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator112}
        name="indicator112"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'13',
      indicator:i18n('entities.dimension1.fields.indicator113'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator113}
        name="indicator113"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator113}
        name="indicator113"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator113}
        name="indicator113"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator113}
        name="indicator113"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator113}
        name="indicator113"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'14',
      indicator:i18n('entities.dimension1.fields.indicator114'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator114}
        name="indicator114"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator114}
        name="indicator114"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator114}
        name="indicator114"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator114}
        name="indicator114"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension1?.indicator114}
        name="indicator114"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
   
  ]
  const dimension2 =[
    {
      no:'1',
      indicator:i18n('entities.deminsion2.fields.indicator21'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator11}
        name="indicator21"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator21}
        name="indicator21"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator21}
        name="indicator21"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator21}
        name="indicator21"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator21}
        name="indicator21"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'2',
      indicator:i18n('entities.deminsion2.fields.indicator22'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator22}
        name="indicator22"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator22}
        name="indicator22"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator22}
        name="indicator22"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator22}
        name="indicator22"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator22}
        name="indicator22"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'3',
      indicator:i18n('entities.deminsion2.fields.indicator23'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator23}
        name="indicator23"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator23}
        name="indicator23"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator23}
        name="indicator23"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator23}
        name="indicator23"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator23}
        name="indicator23"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'4',
      indicator:i18n('entities.deminsion2.fields.indicator24'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator24}
        name="indicator24"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator24}
        name="indicator24"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator24}
        name="indicator24"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator24}
        name="indicator24"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator24}
        name="indicator24"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'5',
      indicator:i18n('entities.deminsion2.fields.indicator25'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator25}
        name="indicator25"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator25}
        name="indicator25"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator25}
        name="indicator25"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator25}
        name="indicator25"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator25}
        name="indicator25"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'6',
      indicator:i18n('entities.deminsion2.fields.indicator26'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator26}
        name="indicator26"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator26}
        name="indicator26"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator26}
        name="indicator26"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator26}
        name="indicator26"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator26}
        name="indicator26"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'7',
      indicator:i18n('entities.deminsion2.fields.indicator27'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator27}
        name="indicator27"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator27}
        name="indicator27"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator27}
        name="indicator27"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator27}
        name="indicator27"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator27}
        name="indicator27"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'8',
      indicator:i18n('entities.deminsion2.fields.indicator28'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator28}
        name="indicator28"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator28}
        name="indicator28"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator28}
        name="indicator28"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator28}
        name="indicator28"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension2?.indicator28}
        name="indicator28"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },

  ]
  const dimension3 =[
    {
      no:'1',
      indicator:i18n('entities.dimension3.fields.indicator31'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator31}
        name="indicator31"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator31}
        name="indicator31"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator31}
        name="indicator31"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator31}
        name="indicator31"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator31}
        name="indicator31"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'2',
      indicator:i18n('entities.dimension3.fields.indicator32'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator32}
        name="indicator32"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator32}
        name="indicator32"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator32}
        name="indicator32"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator32}
        name="indicator32"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator32}
        name="indicator32"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'3',
      indicator:i18n('entities.dimension3.fields.indicator33'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator33}
        name="indicator33"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator33}
        name="indicator33"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator33}
        name="indicator33"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator33}
        name="indicator33"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator33}
        name="indicator33"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'4',
      indicator:i18n('entities.dimension3.fields.indicator34'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator34}
        name="indicator34"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator34}
        name="indicator34"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator34}
        name="indicator34"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator34}
        name="indicator34"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator34}
        name="indicator34"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'5',
      indicator:i18n('entities.dimension3.fields.indicator35'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator35}
        name="indicator35"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator35}
        name="indicator35"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator35}
        name="indicator35"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator35}
        name="indicator35"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator35}
        name="indicator35"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'6',
      indicator:i18n('entities.dimension3.fields.indicator36'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator36}
        name="indicator36"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator36}
        name="indicator36"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator36}
        name="indicator36"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator36}
        name="indicator36"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator36}
        name="indicator36"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'7',
      indicator:i18n('entities.dimension3.fields.indicator37'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator37}
        name="indicator37"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator37}
        name="indicator37"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator37}
        name="indicator37"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator37}
        name="indicator37"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator37}
        name="indicator37"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'8',
      indicator:i18n('entities.dimension3.fields.indicator38'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator38}
        name="indicator38"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator38}
        name="indicator38"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator38}
        name="indicator38"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator38}
        name="indicator38"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator38}
        name="indicator38"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'9',
      indicator:i18n('entities.dimension3.fields.indicator39'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator39}
        name="indicator39"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator39}
        name="indicator39"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator39}
        name="indicator39"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator39}
        name="indicator39"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator39}
        name="indicator39"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'10',
      indicator:i18n('entities.dimension3.fields.indicator310'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator310}
        name="indicator310"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator310}
        name="indicator310"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator310}
        name="indicator310"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator310}
        name="indicator310"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator310}
        name="indicator310"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'11',
      indicator:i18n('entities.dimension3.fields.indicator311'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator311}
        name="indicator311"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator311}
        name="indicator311"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator311}
        name="indicator311"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator311}
        name="indicator311"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator311}
        name="indicator311"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'12',
      indicator:i18n('entities.dimension3.fields.indicator312'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator312}
        name="indicator312"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator312}
        name="indicator312"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator312}
        name="indicator312"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator312}
        name="indicator312"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator312}
        name="indicator312"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'13',
      indicator:i18n('entities.dimension3.fields.indicator313'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator313}
        name="indicator313"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator313}
        name="indicator313"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator313}
        name="indicator313"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator313}
        name="indicator313"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator313}
        name="indicator313"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'14',
      indicator:i18n('entities.dimension3.fields.indicator314'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator314}
        name="indicator314"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator314}
        name="indicator314"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator314}
        name="indicator314"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator314}
        name="indicator314"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator314}
        name="indicator314"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'13',
      indicator:i18n('entities.dimension3.fields.indicator315'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator315}
        name="indicator315"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator315}
        name="indicator315"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator315}
        name="indicator315"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator315}
        name="indicator315"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension3?.indicator315}
        name="indicator315"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },

  ]
  const dimension4 =[
    {
      no:'1',
      indicator:i18n('entities.dimension4.fields.indicator41'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator41}
        name="indicator41"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator41}
        name="indicator41"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator41}
        name="indicator41"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator41}
        name="indicator41"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator41}
        name="indicator41"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'2',
      indicator:i18n('entities.dimension4.fields.indicator42'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator42}
        name="indicator42"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator42}
        name="indicator42"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator42}
        name="indicator42"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator42}
        name="indicator42"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator42}
        name="indicator42"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'3',
      indicator:i18n('entities.dimension4.fields.indicator43'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator43}
        name="indicator43"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator43}
        name="indicator43"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator43}
        name="indicator43"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator43}
        name="indicator43"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator43}
        name="indicator43"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'4',
      indicator:i18n('entities.dimension4.fields.indicator44'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator44}
        name="indicator44"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator44}
        name="indicator44"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator44}
        name="indicator44"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator44}
        name="indicator44"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension4?.indicator44}
        name="indicator44"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
  ]
  const dimension5 =[
    {
      no:'',
      indicator:(<Title level={3}>Lesson Preparation</Title>),
    },
    {
      no:'1',
      indicator:i18n('entities.dimension5.fields.indicator51'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator51}
        name="indicator51"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator51}
        name="indicator51"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator51}
        name="indicator51"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator51}
        name="indicator51"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator51}
        name="indicator51"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'2',
      indicator:i18n('entities.dimension5.fields.indicator52'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator52}
        name="indicator52"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator52}
        name="indicator52"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator52}
        name="indicator52"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator52}
        name="indicator52"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator52}
        name="indicator52"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'3',
      indicator:i18n('entities.dimension5.fields.indicator53'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator53}
        name="indicator53"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator53}
        name="indicator53"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator53}
        name="indicator53"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator53}
        name="indicator53"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator53}
        name="indicator53"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'4',
      indicator:i18n('entities.dimension5.fields.indicator54'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator54}
        name="indicator54"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator54}
        name="indicator54"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator54}
        name="indicator54"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator54}
        name="indicator54"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator54}
        name="indicator54"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'5',
      indicator:i18n('entities.dimension5.fields.indicator55'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator55}
        name="indicator55"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator55}
        name="indicator55"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator55}
        name="indicator55"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator55}
        name="indicator55"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator55}
        name="indicator55"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
   
    {
      no:'6',
      indicator:i18n('entities.dimension5.fields.indicator56'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator56}
        name="indicator56"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator56}
        name="indicator56"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator56}
        name="indicator56"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator56}
        name="indicator56"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator56}
        name="indicator56"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'',
      indicator:(<Title level={3}>Classroom Management</Title>),
    },
    {
      no:'7',
      indicator:i18n('entities.dimension5.fields.indicator57'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator57}
        name="indicator57"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator57}
        name="indicator57"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator57}
        name="indicator57"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator57}
        name="indicator57"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator57}
        name="indicator57"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'8',
      indicator:i18n('entities.dimension5.fields.indicator58'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'9',
      indicator:i18n('entities.dimension5.fields.indicator59'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator58}
        name="indicator58"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'10',
      indicator:i18n('entities.dimension5.fields.indicator510'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator510}
        name="indicator510"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator510}
        name="indicator510"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator510}
        name="indicator510"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator510}
        name="indicator510"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator510}
        name="indicator510"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'11',
      indicator:i18n('entities.dimension5.fields.indicator511'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator511}
        name="indicator511"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator511}
        name="indicator511"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator511}
        name="indicator511"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator511}
        name="indicator511"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator511}
        name="indicator511"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'12',
      indicator:i18n('entities.dimension5.fields.indicator512'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator512}
        name="indicator512"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator512}
        name="indicator512"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator512}
        name="indicator512"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator512}
        name="indicator512"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator512}
        name="indicator512"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'',
      indicator:(<Title level={3}>Instruction</Title>),
    },
    {
      no:'13',
      indicator:i18n('entities.dimension5.fields.indicator513'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator513}
        name="indicator513"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator513}
        name="indicator513"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator513}
        name="indicator513"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator513}
        name="indicator513"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator513}
        name="indicator513"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'14',
      indicator:i18n('entities.dimension5.fields.indicator514'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator514}
        name="indicator514"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator514}
        name="indicator514"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator514}
        name="indicator514"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator514}
        name="indicator514"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator514}
        name="indicator514"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'',
      indicator:(<Title level={3}>Learner Assessment and Feedback</Title>),
    },
    {
      no:'15',
      indicator:i18n('entities.dimension5.fields.indicator515'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator515}
        name="indicator515"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator515}
        name="indicator515"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator515}
        name="indicator515"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator515}
        name="indicator515"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator515}
        name="indicator515"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'16',
      indicator:i18n('entities.dimension5.fields.indicator516'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator516}
        name="indicator516"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator516}
        name="indicator516"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator516}
        name="indicator516"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator516}
        name="indicator516"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator516}
        name="indicator516"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'17',
      indicator:i18n('entities.dimension5.fields.indicator517'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator517}
        name="indicator517"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator517}
        name="indicator517"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator517}
        name="indicator517"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator517}
        name="indicator517"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator517}
        name="indicator517"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'18',
      indicator:i18n('entities.dimension5.fields.indicator518'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator518}
        name="indicator518"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator518}
        name="indicator518"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator518}
        name="indicator518"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator518}
        name="indicator518"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator518}
        name="indicator518"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'19',
      indicator:i18n('entities.dimension5.fields.indicator519'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator519}
        name="indicator519"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator519}
        name="indicator519"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator519}
        name="indicator519"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator519}
        name="indicator519"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator519}
        name="indicator519"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
    {
      no:'20',
      indicator:i18n('entities.dimension5.fields.indicator520'),
      1:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator520}
        name="indicator520"
        size={'large'}
        value={'1'}
        required={false}
        layout={formItemLayout}
      />),
      2:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator520}
        name="indicator520"
        size={'large'}
        value={'2'}
        required={false}
        layout={formItemLayout}
      />),
      3:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator520}
        name="indicator520"
        size={'large'}
        value={'3'}
        required={false}
        layout={formItemLayout}
      />),
      4:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator520}
        name="indicator520"
        size={'large'}
        value={'4'}
        required={false}
        layout={formItemLayout}
      />),
      5:(<CustomCheckboxViewItem
        record={record?.dimension5?.indicator520}
        name="indicator520"
        size={'large'}
        value={'5'}
        required={false}
        layout={formItemLayout}
      />)
    },
   
  ]

  if (loading || !record) {
    return <Spinner />;
  }

  return (
    <ViewWrapper>
       <Row>
            <Col span={24}>
            <Title level={3}>
              {i18n('entities.sSASurvey.new.sectiona')}
              </Title>
              <Text>
              {i18n('entities.sSASurvey.new.introduction')}
              </Text>
              
            </Col>
            
            </Row>
            
            <br/>
            <Row>
            <Col span={24}>
              <Title level={5} style={{color:'red'}} >NOTE:</Title>
            </Col>
            <Col span={24}>
              <Text>
              {i18n('entities.sSASurvey.new.note')}
              </Text>
            </Col>
        </Row>
        <br/>
        <br/>
        <br/>
        <Card title={i18n('entities.sSASurvey.new.basic')}>
            <Row gutter={24}>
              <Col  span={24}>
              {Boolean(record.school?.schoolName) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolName')}
                >
                  {record?.school?.schoolName}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolLevel) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolLevel')}
                >
                  {(record?.school?.schoolLevel || []).map((value) => (
                    <div key={value}>
                      {i18n(
                        `entities.school.enumerators.schoolLevel.${value}`,
                      )}
                    </div>
                  ))}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolType) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolType')}
                >
                  {i18n(
                    `entities.school.enumerators.schoolType.${record?.school?.schoolType}`,
                  )}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolPhone) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolPhone')}
                >
                  {record?.school?.schoolPhone}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolEmail) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolEmail')}
                >
                  {record?.school?.schoolEmail}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolLocation) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolLocation')}
                >
                  {record?.school?.schoolLocation}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.schoolEMISNumber) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.schoolEMISNumber')}
                >
                  {record?.school?.schoolEMISNumber}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.classes) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.classes')}
                >
                  {record?.school?.classes}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.toilets) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.toilets')}
                >
                  {record?.school?.toilets}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.maleStaff) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.maleStaff')}
                >
                  {record?.school?.maleStaff}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.femaleStaff) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.femaleStaff')}
                >
                  {record?.school?.femaleStaff}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.nonTeachingFemaleStaff) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.nonTeachingFemaleStaff')}
                >
                  {record?.school?.nonTeachingFemaleStaff}
                </Form.Item>
              )}
              </Col>
              <Col  {...sexColumnsResponsiveProps}>
              {Boolean(record.school?.nonTeachingMaleStaff) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.nonTeachingMaleStaff')}
                >
                  {record?.school?.nonTeachingMaleStaff}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.headTeacher) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.headTeacher')}
                >
                  {record?.school?.headTeacher}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.headsex) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.headsex')}
                >
                  {i18n(
                    `entities.school.enumerators.headsex.${record.school?.headsex}`,
                  )}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.headTeacherPhone) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.headTeacherPhone')}
                >
                  {record?.school?.headTeacherPhone}
                </Form.Item>
              )}
              </Col>
              <Col  {...threeColumnsResponsiveProps}>
              {Boolean(record.school?.headTeacherLevelEduction) && (
                <Form.Item
                  {...viewItemLayout}
                  labelAlign="left"
                  label={i18n('entities.school.fields.headTeacherLevelEduction')}
                >
                  {record?.school?.headTeacherLevelEduction}
                </Form.Item>
              )}
              </Col>
            </Row>

          </Card>
          <br /><br /><br /><br />

        <Row>
            <Col span={24}>
              <Title level={3}>
              {i18n('entities.sSASurvey.new.sectionb')}
              </Title>
              <Text>
              {i18n('entities.sSASurvey.new.introduction')}
              </Text>
              
            </Col>
            <br /><br />
            <Col span={24}>
              <Table
                rowKey="id"
                columns={columns as any}
                dataSource={data}
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />
            </Col>
        </Row>
        <br /><br /><br /><br />

          <Card title={i18n('entities.sSASurvey.new.dimension1')} style={{padding:0}}>
              <Table
                rowKey="id"
                columns={dimensionColumns as any}
                dataSource={dimension1}
                bordered
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />

          </Card>
          <br /><br /><br /><br />
          <Card title={i18n('entities.sSASurvey.new.dimension2')}>
              <Table
                rowKey="id"
                columns={dimensionColumns as any}
                dataSource={dimension2}
                bordered
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />

          </Card>
          <br /><br /><br /><br />
          <Card title={i18n('entities.sSASurvey.new.dimension3')}>
              <Table
                rowKey="id"
                columns={dimensionColumns as any}
                dataSource={dimension3}
                bordered
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />

          </Card>
          <br /><br /><br /><br />
          <Card title={i18n('entities.sSASurvey.new.dimension4')}>
              <Table
                rowKey="id"
                columns={dimensionColumns as any}
                dataSource={dimension4}
                bordered
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />

          </Card>
          <br /><br /><br /><br />
          <Card title={i18n('entities.sSASurvey.new.dimension5')}>
              <Table
                rowKey="id"
                columns={dimensionColumns as any}
                dataSource={dimension5}
                bordered
                scroll={{
                  x: true,
                }}
                pagination= {false}
              />

          </Card>

         <Row gutter={24}>
          <Col {...twoColumnsResponsiveProps}>  
      {Boolean(record.finalizedDate) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.sSASurvey.fields.finalizedDate')}
        >
          {record.finalizedDate}
        </Form.Item>
      )}
      </Col>
      <Col {...twoColumnsResponsiveProps}>  

      {Boolean(record.principal) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.sSASurvey.fields.principal')}
        >
          {record.principal}
        </Form.Item>
      )}
      </Col>
      <Col {...twoColumnsResponsiveProps}>  

      {Boolean(record.signatureofprincipal) && Boolean(record.signatureofprincipal.length) && (
          <Form.Item
            {...viewItemLayout}
            labelAlign='left'
            label={i18n('entities.sSASurvey.fields.signatureofprincipal')}
          >
            <ImagesViewer value={record.signatureofprincipal} />
          </Form.Item>
        )}
</Col>
<Col {...twoColumnsResponsiveProps}>  

      {Boolean(record.schoolStamp) && Boolean(record.schoolStamp.length) && (
          <Form.Item
            {...viewItemLayout}
            labelAlign='left'
            label={i18n('entities.sSASurvey.fields.schoolStamp')}
          >
            <ImagesViewer value={record.schoolStamp} />
          </Form.Item>
        )}
        </Col>
        </Row>
    </ViewWrapper>
  );
};

export default SSASurveyView;
