import { Table,Form, Typography,Card,Collapse,Row, Col,  } from 'antd';
import { i18n } from 'src/i18n';
import actions from 'src/modules/dimensionSsv3/list/dimensionSsv3ListActions';
import selectors from 'src/modules/dimensionSsv3/list/dimensionSsv3ListSelectors';
import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useAppDispatch } from 'src/modules/hook';
import TableWrapper from 'src/view/shared/styles/TableWrapper';
import CustomCheckboxViewItem from 'src/view/shared/form/items/CustomCheckboxViewItem';
import { formItemLayout } from 'src/view/shared/styles/FormWrapper';
import type { CollapseProps } from 'antd';

const {  Title } = Typography;

const DimensionSsv3ListTable = (props) => {
  const dispatch = useAppDispatch();
  const rawFilter = useSelector(selectors.selectRawFilter);

  const rows = useSelector(selectors.selectRows);
 

  useEffect(() => {
    dispatch(actions.doFetch({supervision:props.supervision?.id}, {supervision:props.supervision?.id}));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);


  const twoColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 8,
    lg: 8,
    xl: 8,
    style: {
      marginBottom: 24,
      padding:5
    },
  };


    const dimensionColumns = [
      {
        title: i18n('entities.sSASurvey.fields.No'),
        sorter: true,
        dataIndex: 'no',   
        width:'5%'
      },
      {
        title: i18n('entities.sSASurvey.fields.Indicator'),
        sorter: true,
        dataIndex: 'indicator',
        width:'50%'
      },
      {
        title: i18n('entities.sSASurvey.fields.1'),
        sorter: true,
        dataIndex: '1',
        width:'10%'
      },
      {
        title: i18n('entities.sSASurvey.fields.2'),
        sorter: true,
        dataIndex: '2',
        width:'10%'
      },
      {
        title: i18n('entities.sSASurvey.fields.3'),
        sorter: true,
        dataIndex: '3',
        width:'5%'
      },
      {
        title: i18n('entities.sSASurvey.fields.4'),
        sorter: true,
        dataIndex: '4',
        width:'5%'
      },
      {
        title: i18n('entities.sSASurvey.fields.5'),
        sorter: true,
        dataIndex: '5',
        width:'5%'
      },
      
    ];

    const items: CollapseProps['items'] = rows?.map((row, index)=>(
      {
        key: `${index+1}`,
        label: 'Record '+(index+1)+' ',
        children: (
          <Card title={i18n('entities.sSASurvey.new.dimension5')}>
             <Row>
             <Col  {...twoColumnsResponsiveProps}>
        {Boolean(row.gradesTaught) && (
          <Form.Item
            labelAlign='left'
            label={i18n('entities.governmentTeacherInformation.fields.gradesTaught')}
          >
            {(row.gradesTaught || []).map((value) => (
              <div key={value}>
                {i18n(
                  `entities.governmentTeacherInformation.enumerators.gradesTaught.${value}`,
                )}
              </div>
            ))}
          </Form.Item>
        )}
        </Col>
        <Col  {...twoColumnsResponsiveProps}>
        {Boolean(row.subjectsTaught) && (
          <Form.Item
            labelAlign='left'
            label={i18n('entities.governmentTeacherInformation.fields.subjectsTaught')}
          >
            {(row.subjectsTaught || []).map((value) => (
              <div key={value}>
                {i18n(
                  `entities.governmentTeacherInformation.enumerators.subjectsTaught.${value}`,
                )}
              </div>
            ))}
          </Form.Item>
        )}
        </Col>
        </Row>
          <Table
            rowKey="id"
            columns={dimensionColumns as any}
            dataSource={[
              {
                no:'',
                indicator:(<Title level={3}>Lesson Preparation</Title>),
              },
              {
                no:'1',
                indicator:i18n('entities.dimension5.fields.indicator51'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator51}
                  name="indicator51"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator51}
                  name="indicator51"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator51}
                  name="indicator51"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator51}
                  name="indicator51"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator51}
                  name="indicator51"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'2',
                indicator:i18n('entities.dimension5.fields.indicator52'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator52}
                  name="indicator52"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator52}
                  name="indicator52"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator52}
                  name="indicator52"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator52}
                  name="indicator52"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator52}
                  name="indicator52"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'3',
                indicator:i18n('entities.dimension5.fields.indicator53'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator53}
                  name="indicator53"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator53}
                  name="indicator53"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator53}
                  name="indicator53"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator53}
                  name="indicator53"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator53}
                  name="indicator53"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'4',
                indicator:i18n('entities.dimension5.fields.indicator54'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator54}
                  name="indicator54"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator54}
                  name="indicator54"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator54}
                  name="indicator54"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator54}
                  name="indicator54"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator54}
                  name="indicator54"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'5',
                indicator:i18n('entities.dimension5.fields.indicator55'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator55}
                  name="indicator55"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator55}
                  name="indicator55"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator55}
                  name="indicator55"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator55}
                  name="indicator55"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator55}
                  name="indicator55"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
             
              {
                no:'6',
                indicator:i18n('entities.dimension5.fields.indicator56'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator56}
                  name="indicator56"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator56}
                  name="indicator56"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator56}
                  name="indicator56"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator56}
                  name="indicator56"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator56}
                  name="indicator56"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'',
                indicator:(<Title level={3}>Classroom Management</Title>),
              },
              {
                no:'7',
                indicator:i18n('entities.dimension5.fields.indicator57'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator57}
                  name="indicator57"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator57}
                  name="indicator57"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator57}
                  name="indicator57"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator57}
                  name="indicator57"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator57}
                  name="indicator57"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'8',
                indicator:i18n('entities.dimension5.fields.indicator58'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'9',
                indicator:i18n('entities.dimension5.fields.indicator59'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator58}
                  name="indicator58"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'10',
                indicator:i18n('entities.dimension5.fields.indicator510'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator510}
                  name="indicator510"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator510}
                  name="indicator510"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator510}
                  name="indicator510"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator510}
                  name="indicator510"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator510}
                  name="indicator510"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'11',
                indicator:i18n('entities.dimension5.fields.indicator511'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator511}
                  name="indicator511"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator511}
                  name="indicator511"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator511}
                  name="indicator511"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator511}
                  name="indicator511"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator511}
                  name="indicator511"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'12',
                indicator:i18n('entities.dimension5.fields.indicator512'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator512}
                  name="indicator512"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator512}
                  name="indicator512"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator512}
                  name="indicator512"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator512}
                  name="indicator512"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator512}
                  name="indicator512"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'',
                indicator:(<Title level={3}>Instruction</Title>),
              },
              {
                no:'13',
                indicator:i18n('entities.dimension5.fields.indicator513'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator513}
                  name="indicator513"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator513}
                  name="indicator513"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator513}
                  name="indicator513"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator513}
                  name="indicator513"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator513}
                  name="indicator513"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'14',
                indicator:i18n('entities.dimension5.fields.indicator514'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator514}
                  name="indicator514"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator514}
                  name="indicator514"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator514}
                  name="indicator514"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator514}
                  name="indicator514"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator514}
                  name="indicator514"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'',
                indicator:(<Title level={3}>Learner Assessment and Feedback</Title>),
              },
              {
                no:'15',
                indicator:i18n('entities.dimension5.fields.indicator515'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator515}
                  name="indicator515"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator515}
                  name="indicator515"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator515}
                  name="indicator515"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator515}
                  name="indicator515"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator515}
                  name="indicator515"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'16',
                indicator:i18n('entities.dimension5.fields.indicator516'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator516}
                  name="indicator516"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator516}
                  name="indicator516"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator516}
                  name="indicator516"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator516}
                  name="indicator516"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator516}
                  name="indicator516"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'17',
                indicator:i18n('entities.dimension5.fields.indicator517'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator517}
                  name="indicator517"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator517}
                  name="indicator517"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator517}
                  name="indicator517"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator517}
                  name="indicator517"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator517}
                  name="indicator517"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'18',
                indicator:i18n('entities.dimension5.fields.indicator518'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator518}
                  name="indicator518"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator518}
                  name="indicator518"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator518}
                  name="indicator518"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator518}
                  name="indicator518"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator518}
                  name="indicator518"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'19',
                indicator:i18n('entities.dimension5.fields.indicator519'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator519}
                  name="indicator519"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator519}
                  name="indicator519"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator519}
                  name="indicator519"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator519}
                  name="indicator519"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator519}
                  name="indicator519"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
              {
                no:'20',
                indicator:i18n('entities.dimension5.fields.indicator520'),
                1:(<CustomCheckboxViewItem
                  record={row?.indicator520}
                  name="indicator520"
                  size={'large'}
                  value={'1'}
                  required={false}
                  layout={formItemLayout}
                />),
                2:(<CustomCheckboxViewItem
                  record={row?.indicator520}
                  name="indicator520"
                  size={'large'}
                  value={'2'}
                  required={false}
                  layout={formItemLayout}
                />),
                3:(<CustomCheckboxViewItem
                  record={row?.indicator520}
                  name="indicator520"
                  size={'large'}
                  value={'3'}
                  required={false}
                  layout={formItemLayout}
                />),
                4:(<CustomCheckboxViewItem
                  record={row?.indicator520}
                  name="indicator520"
                  size={'large'}
                  value={'4'}
                  required={false}
                  layout={formItemLayout}
                />),
                5:(<CustomCheckboxViewItem
                  record={row?.indicator520}
                  name="indicator520"
                  size={'large'}
                  value={'5'}
                  required={false}
                  layout={formItemLayout}
                />)
              },
             
            ]
            }
            bordered
            scroll={{
              x: true,
            }}
            pagination= {false}
          />

      </Card>),
      }
    ))
  return (
    <TableWrapper>
      <Collapse items={items} defaultActiveKey={['1']} />
    </TableWrapper>
  );
};

export default DimensionSsv3ListTable;
