import React from 'react';
import Spinner from 'src/view/shared/Spinner';
import  {
  viewItemLayout,
} from 'src/view/shared/styles/ViewWrapper';
import { i18n } from 'src/i18n';
import { Form , Row, Col, Table,Tabs, Card} from 'antd';
import CustomCheckboxViewItem from 'src/view/shared/form/items/CustomCheckboxViewItem'
import {
  formItemLayout,
} from 'src/view/shared/styles/FormWrapper';
import DimensionSsv3ListPage from 'src/view/dimensionSsv3/list/DimensionSsv3ListPage';

const SchoolSupervisionView = (props) => {
  const { record, loading } = props;
  const threeColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 8,
    lg: 8,
    xl: 8,
    style: {
      marginBottom: 24,
    },
  };


  const sexColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 4,
    lg: 4,
    xl: 4,
    style: {
      marginBottom: 24,
    },
  };

    
      const dimensionColumns = [
        {
          title: i18n('entities.sSASurvey.fields.No'),
          sorter: true,
          dataIndex: 'no',   
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.Indicator'),
          sorter: true,
          dataIndex: 'indicator',
          width:'50%'
        },
        {
          title: i18n('entities.sSASurvey.fields.1'),
          sorter: true,
          dataIndex: '1',
          width:'10%'
        },
        {
          title: i18n('entities.sSASurvey.fields.2'),
          sorter: true,
          dataIndex: '2',
          width:'10%'
        },
        {
          title: i18n('entities.sSASurvey.fields.3'),
          sorter: true,
          dataIndex: '3',
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.4'),
          sorter: true,
          dataIndex: '4',
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.5'),
          sorter: true,
          dataIndex: '5',
          width:'5%'
        },
        
      ];

    const dimension1 =[
      {
        no:'1',
        indicator:i18n('entities.dimension1.fields.indicator11'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator11}
          name="indicator11"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator11}
          name="indicator11"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator11}
          name="indicator11"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator11}
          name="indicator11"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator11}
          name="indicator11"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'2',
        indicator:i18n('entities.dimension1.fields.indicator12'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator12}
          name="indicator12"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator12}
          name="indicator12"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator12}
          name="indicator12"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator12}
          name="indicator12"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator12}
          name="indicator12"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'3',
        indicator:i18n('entities.dimension1.fields.indicator13'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator13}
          name="indicator13"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator13}
          name="indicator13"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator13}
          name="indicator13"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator13}
          name="indicator13"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator13}
          name="indicator13"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'4',
        indicator:i18n('entities.dimension1.fields.indicator14'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator14}
          name="indicator14"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator14}
          name="indicator14"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator14}
          name="indicator14"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator14}
          name="indicator14"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator14}
          name="indicator14"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'5',
        indicator:i18n('entities.dimension1.fields.indicator15'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator15}
          name="indicator15"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator15}
          name="indicator15"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator15}
          name="indicator15"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator15}
          name="indicator15"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator15}
          name="indicator15"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'6',
        indicator:i18n('entities.dimension1.fields.indicator16'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator16}
          name="indicator16"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator16}
          name="indicator16"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator16}
          name="indicator16"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator16}
          name="indicator16"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator16}
          name="indicator16"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'7',
        indicator:i18n('entities.dimension1.fields.indicator17'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator17}
          name="indicator17"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator17}
          name="indicator17"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator17}
          name="indicator17"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator17}
          name="indicator17"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator17}
          name="indicator17"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'8',
        indicator:i18n('entities.dimension1.fields.indicator18'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator18}
          name="indicator18"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator18}
          name="indicator18"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator18}
          name="indicator18"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator18}
          name="indicator18"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator18}
          name="indicator18"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'9',
        indicator:i18n('entities.dimension1.fields.indicator19'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator19}
          name="indicator19"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator19}
          name="indicator19"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator19}
          name="indicator19"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator19}
          name="indicator19"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator19}
          name="indicator19"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'10',
        indicator:i18n('entities.dimension1.fields.indicator110'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator110}
          name="indicator110"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator110}
          name="indicator110"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator110}
          name="indicator110"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator110}
          name="indicator110"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator110}
          name="indicator110"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'11',
        indicator:i18n('entities.dimension1.fields.indicator111'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator111}
          name="indicator111"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator111}
          name="indicator111"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator111}
          name="indicator111"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator111}
          name="indicator111"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator111}
          name="indicator111"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'12',
        indicator:i18n('entities.dimension1.fields.indicator112'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator112}
          name="indicator112"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator112}
          name="indicator112"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator112}
          name="indicator112"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator112}
          name="indicator112"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator112}
          name="indicator112"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'13',
        indicator:i18n('entities.dimension1.fields.indicator113'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator113}
          name="indicator113"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator113}
          name="indicator113"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator113}
          name="indicator113"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator113}
          name="indicator113"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator113}
          name="indicator113"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'14',
        indicator:i18n('entities.dimension1.fields.indicator114'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator114}
          name="indicator114"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator114}
          name="indicator114"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator114}
          name="indicator114"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator114}
          name="indicator114"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension1?.indicator114}
          name="indicator114"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
    
    ]

    const dimension3 =[
      {
        no:'1',
        indicator:i18n('entities.dimension3.fields.indicator31'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator31}
          name="indicator31"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator31}
          name="indicator31"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator31}
          name="indicator31"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator31}
          name="indicator31"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator31}
          name="indicator31"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'2',
        indicator:i18n('entities.dimension3.fields.indicator32'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator32}
          name="indicator32"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator32}
          name="indicator32"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator32}
          name="indicator32"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator32}
          name="indicator32"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator32}
          name="indicator32"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'3',
        indicator:i18n('entities.dimension3.fields.indicator33'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator33}
          name="indicator33"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator33}
          name="indicator33"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator33}
          name="indicator33"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator33}
          name="indicator33"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator33}
          name="indicator33"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'4',
        indicator:i18n('entities.dimension3.fields.indicator34'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator34}
          name="indicator34"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator34}
          name="indicator34"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator34}
          name="indicator34"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator34}
          name="indicator34"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator34}
          name="indicator34"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'5',
        indicator:i18n('entities.dimension3.fields.indicator35'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator35}
          name="indicator35"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator35}
          name="indicator35"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator35}
          name="indicator35"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator35}
          name="indicator35"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator35}
          name="indicator35"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'6',
        indicator:i18n('entities.dimension3.fields.indicator36'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator36}
          name="indicator36"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator36}
          name="indicator36"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator36}
          name="indicator36"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator36}
          name="indicator36"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator36}
          name="indicator36"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'7',
        indicator:i18n('entities.dimension3.fields.indicator37'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator37}
          name="indicator37"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator37}
          name="indicator37"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator37}
          name="indicator37"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator37}
          name="indicator37"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator37}
          name="indicator37"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'8',
        indicator:i18n('entities.dimension3.fields.indicator38'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator38}
          name="indicator38"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator38}
          name="indicator38"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator38}
          name="indicator38"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator38}
          name="indicator38"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator38}
          name="indicator38"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'9',
        indicator:i18n('entities.dimension3.fields.indicator39'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator39}
          name="indicator39"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator39}
          name="indicator39"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator39}
          name="indicator39"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator39}
          name="indicator39"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator39}
          name="indicator39"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'10',
        indicator:i18n('entities.dimension3.fields.indicator310'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator310}
          name="indicator310"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator310}
          name="indicator310"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator310}
          name="indicator310"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator310}
          name="indicator310"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator310}
          name="indicator310"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'11',
        indicator:i18n('entities.dimension3.fields.indicator311'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator311}
          name="indicator311"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator311}
          name="indicator311"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator311}
          name="indicator311"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator311}
          name="indicator311"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator311}
          name="indicator311"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'12',
        indicator:i18n('entities.dimension3.fields.indicator312'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator312}
          name="indicator312"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator312}
          name="indicator312"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator312}
          name="indicator312"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator312}
          name="indicator312"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator312}
          name="indicator312"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'13',
        indicator:i18n('entities.dimension3.fields.indicator313'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator313}
          name="indicator313"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator313}
          name="indicator313"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator313}
          name="indicator313"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator313}
          name="indicator313"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator313}
          name="indicator313"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'14',
        indicator:i18n('entities.dimension3.fields.indicator314'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator314}
          name="indicator314"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator314}
          name="indicator314"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator314}
          name="indicator314"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator314}
          name="indicator314"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator314}
          name="indicator314"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
      {
        no:'13',
        indicator:i18n('entities.dimension3.fields.indicator315'),
        1:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator315}
          name="indicator315"
          size={'large'}
          value={'1'}
          required={false}
          layout={formItemLayout}
        />),
        2:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator315}
          name="indicator315"
          size={'large'}
          value={'2'}
          required={false}
          layout={formItemLayout}
        />),
        3:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator315}
          name="indicator315"
          size={'large'}
          value={'3'}
          required={false}
          layout={formItemLayout}
        />),
        4:(<CustomCheckboxViewItem
          record={record?.dimension2?.indicator315}
          name="indicator315"
          size={'large'}
          value={'4'}
          required={false}
          layout={formItemLayout}
        />),
        5:(<CustomCheckboxViewItem
          record={record?.dimension3?.indicator315}
          name="indicator315"
          size={'large'}
          value={'5'}
          required={false}
          layout={formItemLayout}
        />)
      },
  
    ]


    if (loading || !record) {
      return <Spinner />;
    }

  return (
    <>
          <Tabs
            defaultActiveKey="0"
            size="large"
            type="card"
            style={{ marginTop: 0, backgroundColor:'white' }}
            tabBarStyle={{ marginTop: 0, backgroundColor:'#f5f5f5' }}
            items={[
              {
                label:i18n('entities.sSASurvey.new.basic'),
                key: '0',
                children: (
                  <Card title={i18n('entities.sSASurvey.new.basic')}>
                  <Row gutter={24}>
                    <Col  span={24}>
                    {Boolean(record.school?.schoolName) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolName')}
                      >
                        {record?.school?.schoolName}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolLevel) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolLevel')}
                      >
                        {(record?.school?.schoolLevel || []).map((value) => (
                          <div key={value}>
                            {i18n(
                              `entities.school.enumerators.schoolLevel.${value}`,
                            )}
                          </div>
                        ))}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolType) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolType')}
                      >
                        {i18n(
                          `entities.school.enumerators.schoolType.${record?.school?.schoolType}`,
                        )}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolPhone) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolPhone')}
                      >
                        {record?.school?.schoolPhone}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolEmail) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolEmail')}
                      >
                        {record?.school?.schoolEmail}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolLocation) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolLocation')}
                      >
                        {record?.school?.schoolLocation}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.schoolEMISNumber) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.schoolEMISNumber')}
                      >
                        {record?.school?.schoolEMISNumber}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.classes) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.classes')}
                      >
                        {record?.school?.classes}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.toilets) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.toilets')}
                      >
                        {record?.school?.toilets}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.maleStaff) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.maleStaff')}
                      >
                        {record?.school?.maleStaff}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.femaleStaff) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.femaleStaff')}
                      >
                        {record?.school?.femaleStaff}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.nonTeachingFemaleStaff) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.nonTeachingFemaleStaff')}
                      >
                        {record?.school?.nonTeachingFemaleStaff}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...sexColumnsResponsiveProps}>
                    {Boolean(record.school?.nonTeachingMaleStaff) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.nonTeachingMaleStaff')}
                      >
                        {record?.school?.nonTeachingMaleStaff}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.headTeacher) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.headTeacher')}
                      >
                        {record?.school?.headTeacher}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.headsex) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.headsex')}
                      >
                        {i18n(
                          `entities.school.enumerators.headsex.${record.school?.headsex}`,
                        )}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.headTeacherPhone) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.headTeacherPhone')}
                      >
                        {record?.school?.headTeacherPhone}
                      </Form.Item>
                    )}
                    </Col>
                    <Col  {...threeColumnsResponsiveProps}>
                    {Boolean(record.school?.headTeacherLevelEduction) && (
                      <Form.Item
                        {...viewItemLayout}
                        labelAlign="left"
                        label={i18n('entities.school.fields.headTeacherLevelEduction')}
                      >
                        {record?.school?.headTeacherLevelEduction}
                      </Form.Item>
                    )}
                    </Col>
                  </Row>
      
                </Card>
                ),
              },
              {
                label:i18n('entities.schoolSupervision.fields.dimension1'),
                key: '1',
                children: (
                    <Card title={i18n('entities.schoolSupervision.new.dimension1')} style={{padding:0,marginTop:-20}}>
                                <Table
                                  rowKey="id"
                                  columns={dimensionColumns as any}
                                  dataSource={dimension1}
                                  bordered
                                  scroll={{
                                    x: true,
                                  }}
                                  pagination= {false}
                                />
                  
                   </Card>
                ),
              },
              {
                label:i18n('entities.schoolSupervision.fields.dimension2'),
                key: '2',
                children: (
                   <Card title={i18n('entities.schoolSupervision.new.dimension2')}>
                                 <Table
                                   rowKey="id"
                                   columns={dimensionColumns as any}
                                   dataSource={dimension3}
                                   bordered
                                   scroll={{
                                     x: true,
                                   }}
                                   pagination= {false}
                                 />
                   
                             </Card>
                ),
              },
              {
                label:i18n('entities.schoolSupervision.fields.dimension3'),
                key: '3',
                children: (
                  <DimensionSsv3ListPage
                   supervision={record}
                  />
                ),
              }
            ]}
          />
    </>
  );
};

export default SchoolSupervisionView;
