import React from 'react';
import Spinner from 'src/view/shared/Spinner';
import ViewWrapper, {
  viewItemLayout,
} from 'src/view/shared/styles/ViewWrapper';
import { i18n } from 'src/i18n';
import SchoolViewItem from 'src/view/school/view/SchoolViewItem';
import RegionViewItem from 'src/view/region/view/RegionViewItem';
import DistrictViewItem from 'src/view/district/view/DistrictViewItem';
import CustomCheckboxViewItem from 'src/view/shared/form/items/CustomCheckboxViewItem';
import { formItemLayout } from 'src/view/shared/styles/FormWrapper';
import { Table,Form, Typography,Card,Row, Col,  } from 'antd';

import StateViewItem from 'src/view/state/view/StateViewItem';

const {  Title } = Typography;
const TeacherGPEView = (props) => {
  const { record, loading } = props;

  if (loading || !record) {
    return <Spinner />;
  }
  const dimensionColumns = [
        {
          title: i18n('entities.sSASurvey.fields.No'),
          sorter: true,
          dataIndex: 'no',   
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.Indicator'),
          sorter: true,
          dataIndex: 'indicator',
          width:'50%'
        },
        {
          title: i18n('entities.sSASurvey.fields.1'),
          sorter: true,
          dataIndex: '1',
          width:'10%'
        },
        {
          title: i18n('entities.sSASurvey.fields.2'),
          sorter: true,
          dataIndex: '2',
          width:'10%'
        },
        {
          title: i18n('entities.sSASurvey.fields.3'),
          sorter: true,
          dataIndex: '3',
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.4'),
          sorter: true,
          dataIndex: '4',
          width:'5%'
        },
        {
          title: i18n('entities.sSASurvey.fields.5'),
          sorter: true,
          dataIndex: '5',
          width:'5%'
        },
        
      ];

  const twoColumnsResponsiveProps = {
    xs: 24,
    sm: 24,
    md: 8,
    lg: 8,
    xl: 8,
    style: {
      marginBottom: 24,
      padding:5
    },
  };


  return (
    <ViewWrapper>
        <Row>
        <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.fullName) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.fullName')}
        >
          {record.fullName}
        </Form.Item>
      )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.gender) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.gender')}
        >
          {i18n(
            `entities.teacherGPE.enumerators.gender.${record.gender}`,
          )}
        </Form.Item>
      )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.school) && (
          <Form.Item
            {...viewItemLayout}
            labelAlign='left'
            label={i18n('entities.teacherGPE.fields.school')}
          >
            <SchoolViewItem value={record.school} />
          </Form.Item>
        )}

               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.state) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.state')}
        >
         <StateViewItem value={record.state} />
        </Form.Item>
      )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.region) && (
          <Form.Item
            {...viewItemLayout}
            labelAlign='left'
            label={i18n('entities.teacherGPE.fields.region')}
          >
            <RegionViewItem value={record.region} />
          </Form.Item>
        )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.district) && (
          <Form.Item
            {...viewItemLayout}
            labelAlign='left'
            label={i18n('entities.teacherGPE.fields.district')}
          >
            <DistrictViewItem value={record.district} />
          </Form.Item>
        )}
               </Col>
               
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.subjectName) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.subjectName')}
        >
          {i18n(
            `entities.teacherGPE.enumerators.subjectName.${record.subjectName}`,
          )}
        </Form.Item>
      )}

               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.teachingLevel) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.teachingLevel')}
        >
          {i18n(
            `entities.teacherGPE.enumerators.teachingLevel.${record.teachingLevel}`,
          )}
        </Form.Item>
      )}

               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.grade) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.grade')}
        >
          {i18n(
            `entities.teacherGPE.enumerators.grade.${record.grade}`,
          )}
        </Form.Item>
      )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.totalStudent) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.totalStudent')}
        >
          {record.totalStudent}
        </Form.Item>
      )}
               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.maleStudents) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.maleStudents')}
        >
          {record.maleStudents}
        </Form.Item>
      )}

               </Col>
               <Col  {...twoColumnsResponsiveProps}>
               {Boolean(record.femaleStudent) && (
        <Form.Item
          {...viewItemLayout}
          labelAlign='left'
          label={i18n('entities.teacherGPE.fields.femaleStudent')}
        >
          {record.femaleStudent}
        </Form.Item>
      )}
               </Col>

          </Row>
     
       <Card title={i18n('entities.sSASurvey.new.dimension5')}>
             
            <Table
              rowKey="id"
              columns={dimensionColumns as any}
              dataSource={[
                {
                  no:'',
                  indicator:(<Title level={3}>Lesson Preparation</Title>),
                },
                {
                  no:'1',
                  indicator:i18n('entities.dimension5.fields.indicator51'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator51}
                    name="indicator51"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator51}
                    name="indicator51"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator51}
                    name="indicator51"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator51}
                    name="indicator51"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator51}
                    name="indicator51"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'2',
                  indicator:i18n('entities.dimension5.fields.indicator52'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator52}
                    name="indicator52"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator52}
                    name="indicator52"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator52}
                    name="indicator52"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator52}
                    name="indicator52"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator52}
                    name="indicator52"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'3',
                  indicator:i18n('entities.dimension5.fields.indicator53'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator53}
                    name="indicator53"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator53}
                    name="indicator53"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator53}
                    name="indicator53"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator53}
                    name="indicator53"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator53}
                    name="indicator53"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'4',
                  indicator:i18n('entities.dimension5.fields.indicator54'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator54}
                    name="indicator54"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator54}
                    name="indicator54"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator54}
                    name="indicator54"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator54}
                    name="indicator54"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator54}
                    name="indicator54"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'5',
                  indicator:i18n('entities.dimension5.fields.indicator55'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator55}
                    name="indicator55"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator55}
                    name="indicator55"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator55}
                    name="indicator55"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator55}
                    name="indicator55"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator55}
                    name="indicator55"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
               
                {
                  no:'6',
                  indicator:i18n('entities.dimension5.fields.indicator56'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator56}
                    name="indicator56"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator56}
                    name="indicator56"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator56}
                    name="indicator56"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator56}
                    name="indicator56"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator56}
                    name="indicator56"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'',
                  indicator:(<Title level={3}>Classroom Management</Title>),
                },
                {
                  no:'7',
                  indicator:i18n('entities.dimension5.fields.indicator57'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator57}
                    name="indicator57"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator57}
                    name="indicator57"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator57}
                    name="indicator57"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator57}
                    name="indicator57"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator57}
                    name="indicator57"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'8',
                  indicator:i18n('entities.dimension5.fields.indicator58'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'9',
                  indicator:i18n('entities.dimension5.fields.indicator59'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator58}
                    name="indicator58"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'10',
                  indicator:i18n('entities.dimension5.fields.indicator510'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator510}
                    name="indicator510"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator510}
                    name="indicator510"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator510}
                    name="indicator510"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator510}
                    name="indicator510"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator510}
                    name="indicator510"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'11',
                  indicator:i18n('entities.dimension5.fields.indicator511'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator511}
                    name="indicator511"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator511}
                    name="indicator511"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator511}
                    name="indicator511"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator511}
                    name="indicator511"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator511}
                    name="indicator511"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'12',
                  indicator:i18n('entities.dimension5.fields.indicator512'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator512}
                    name="indicator512"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator512}
                    name="indicator512"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator512}
                    name="indicator512"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator512}
                    name="indicator512"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator512}
                    name="indicator512"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'',
                  indicator:(<Title level={3}>Instruction</Title>),
                },
                {
                  no:'13',
                  indicator:i18n('entities.dimension5.fields.indicator513'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator513}
                    name="indicator513"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator513}
                    name="indicator513"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator513}
                    name="indicator513"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator513}
                    name="indicator513"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator513}
                    name="indicator513"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'14',
                  indicator:i18n('entities.dimension5.fields.indicator514'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator514}
                    name="indicator514"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator514}
                    name="indicator514"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator514}
                    name="indicator514"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator514}
                    name="indicator514"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator514}
                    name="indicator514"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'',
                  indicator:(<Title level={3}>Learner Assessment and Feedback</Title>),
                },
                {
                  no:'15',
                  indicator:i18n('entities.dimension5.fields.indicator515'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator515}
                    name="indicator515"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator515}
                    name="indicator515"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator515}
                    name="indicator515"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator515}
                    name="indicator515"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator515}
                    name="indicator515"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'16',
                  indicator:i18n('entities.dimension5.fields.indicator516'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator516}
                    name="indicator516"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator516}
                    name="indicator516"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator516}
                    name="indicator516"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator516}
                    name="indicator516"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator516}
                    name="indicator516"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'17',
                  indicator:i18n('entities.dimension5.fields.indicator517'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator517}
                    name="indicator517"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator517}
                    name="indicator517"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator517}
                    name="indicator517"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator517}
                    name="indicator517"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator517}
                    name="indicator517"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'18',
                  indicator:i18n('entities.dimension5.fields.indicator518'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator518}
                    name="indicator518"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator518}
                    name="indicator518"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator518}
                    name="indicator518"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator518}
                    name="indicator518"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator518}
                    name="indicator518"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'19',
                  indicator:i18n('entities.dimension5.fields.indicator519'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator519}
                    name="indicator519"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator519}
                    name="indicator519"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator519}
                    name="indicator519"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator519}
                    name="indicator519"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator519}
                    name="indicator519"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
                {
                  no:'20',
                  indicator:i18n('entities.dimension5.fields.indicator520'),
                  1:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator520}
                    name="indicator520"
                    size={'large'}
                    value={'1'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  2:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator520}
                    name="indicator520"
                    size={'large'}
                    value={'2'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  3:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator520}
                    name="indicator520"
                    size={'large'}
                    value={'3'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  4:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator520}
                    name="indicator520"
                    size={'large'}
                    value={'4'}
                    required={false}
                    layout={formItemLayout}
                  />),
                  5:(<CustomCheckboxViewItem
                    record={record?.dimension5?.indicator520}
                    name="indicator520"
                    size={'large'}
                    value={'5'}
                    required={false}
                    layout={formItemLayout}
                  />)
                },
               
              ]
              }
              bordered
              scroll={{
                x: true,
              }}
              pagination= {false}
            />
  
        </Card>),
    </ViewWrapper>
  );
};

export default TeacherGPEView;
